### ISSUE TITLE
Email content is trimmed with Inbox and gmail

### ISSUE THREAD

**Issue by bamos** [andreausu/git-notifier#10]
I took a glance at the HTML and don't see anything obviously causing this. It seems like Inbox/gmail should know to not trim the visible content of a message.
A quick client-side workaround could to use a browser extension that disables trimming like https://chrome.google.com/webstore/detail/trimless-for-google-mail/niepjjjfafhadmfdminbckmciijcaagc, but I prefer trimming for my other emails.

![image](https://cloud.githubusercontent.com/assets/707462/9980843/fb70de76-5f75-11e5-98d7-2d24bda50aae.png)
![image](https://cloud.githubusercontent.com/assets/707462/9980847/103b36d0-5f76-11e5-9192-1c6322ab733b.png)

**Comment by andreausu** [comment]
Thanks for reporting this, I'll try to find a solution as soon as I have some time :)

**Comment by bamos** [comment]
Hi, this is fixed in my most recent git-notifier email - closing. Did you make any changes, or was this on Google's end?

**Comment by andreausu** [comment]
No changes on my side, thank you for the update!

**Comment by bamos** [comment]
Sorry, now my most recent email is trimmed again. Not sure why the one yesterday wasn't.

**Comment by andreausu** [comment]
I've made a few design changes to the emails but I think that the problem is still there, I'm getting it randomly.
I will continue to iterate in the next few days, I really hope to find the cause of this.

**Comment by andreausu** [comment]
So the redesigned emails are up and the issue should be fixed, let me know if you still have problems though :)

**Comment by bamos** [comment]
Awesome, thanks @andreausu!
